function font_init() {
    //var mapstring = "ABCDEFGHIJKLMNOPQRSTUVWXYZ !'#$%&'()*+,-./:;<=>?@[]^_`{}'0123456789abcdefghijklmnopqrstuvwxyz";
    //global.font = font_add_sprite_ext(s_font, mapstring, true, 1);
    var mapstring = " !#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{}~一丁万三上下不与丑专且丙业东丝丢两个中丰串丸为主久么义之乌乐乒乓也习乡书买乱乳了予争事二于互五些亡交产享亮亲人什仁仅今介仍从他仗付仙代令以们仰件价任份仿企伏休优伙会传伤伴但位低住体何余作你使例供侠侥便保信修倍倒候借值假偏做停健偶偷储傻像僵儿允元充先光克免入全公共关兴兵其具典内册再冒军冠冬冰冲决况冷冻净准减凑几凭出击刀刃分切划列刚创初删利别到制刷券刺刻剂削前剑剔剧剩剪割劈力办功加务动助努励劲势勾包匕化匣匹区医十千升午单卖卡卫印危即却卷卸厅厌原去参又友双反发取受变叛叠口古另只叫召可台右叶号司叹吃合吉同名后吐向吗否吧含听启吱吵吸吻呀告员呢周味命和咒咖咪咬咳品哈响哎哑哟哦哪唤售唯唱商啊啡啦啪喜喝喵喷嗜嗯嘻嘿噢器回因团园围固国图圆圈土圣在地场圾坏块坚坦垃型垫埋城域培基堂堆堕堡塑填增士声壳壶处备复夏外多夜够大天太失头夹夺奇奉奏奖套奥女奶她好如妨妻始姐姑姿威娃娘婪嫌子字存孤学孩宁它宇安完官宙定宝实宠客室害宵家容密寒寸对寻导封射将小少尔尖尘尝就尺尽尾局层居屉屋屏属山岩峰巢工左巧巨巫差己已巾币市布师希带帮常帽幅幕干平并幸幻幼庆床序库应底店度座康延建开异弃式弓引张弱弹强归当录形彩影径待很徒得御循微德徽心必忆忌志忘忙快念忽怀态怎怒思急性怪总恋恐恒恢恭息恳恶恼悔悠患您悲情惊惠惧惩惫想惹意感愤愿慈慕慢慧戏成我或战截户房所扇手才扑打扔扣扩扫扬扳批找承技把抑抓投抖抗折抛抢护报抱抵押抽担拍拒拖招拟拥择拳拾拿持指按挑挖挡挤挥振捉捕损捡换据捷掉掌排掘探接控推掩掷提握援搏搜搞搭携摄摇撕撞撤播撼擅操擦攒支收改攻放故效敌救教敢散数整文斗料斩断新方旋族无日旧旨早时明易星是显晕晚普景晰晶智暂暗暴更曾替最月有朋服望朝期木未本术机朽杀杆杏杖束杠条来杯松板极构析枕林枚果枪架柄某染柜柠查柱标校株样根格框桌档桥桶梁梦检棍棒棘森棵椅植椒椭概榜槽模横橙欠次欢款歇歉歌止正此步武歪死段毁母每毒比毙毛毫毯气氛氧水永汁求池汪汽沉沙没河油治沿法泡波注泰泳洁洋洛活派流浇测浏浓浪浮海涂消涉涡液深混添清渔游溅源溜滑滚满滴漏演漫激灌火灭灯灵炸点炼烟烤烦烧热焦焰然照熄熊熟燃爆爪爱片版牌牙牛物牵特犯状狂狗狙狩独狼猎猛猪猫献率王玩环现珍珠班球理瑕瓜瓣瓶生用由甲电画畅界畏留略疑疗疤疫疲疼病痕痛白百的皇皮盒盔盖盘目盯直相盹盾省看真眨眩眼着睁睛睡瞄瞬矛矢知矩短石矿砍破砸砺硬确碍碎碗碰碳磁磅磨示礼祝神禁离私种秒积称移稀程稍稳穴穷空穿突窗窝立站章竿笑笔符第笼等筑筒策筛签简算箭箱篮籍米类粉粘精糕糖糟系素索紧紫繁纠红级纱纸线练组终绊绍经绑绒结绕绘给绝统继绪续绵绿缆缓编缚缩罐网罩置美群羽翻翼老考者而耐耗联聚肤胀背胜胶能脆脉脑脚脱腹膨臂自至致舞色节芋芒花苏苗苦英范茄茶荆草荡药获莹菌菜萄落葡葱蒜蓄蓝蔬蕉薪藏虎虾蛋蜂螺血行衣补表衫袋被袭裂装西要见观规视览觉角解触言誓警计订认讨让训议记讲许设证评诅译试话该语误诱说请读课谁调谈谐谓谢谷豆象貌贝负财败货质贪购贯贴费资赋赏赛赞赢走起趁超越趣足趾跃跑距跟路跳踪躁身躲车转轮软轴轻载较辑输辣辨边达迅过迎运近返还这进远违连迟迪迫追退送适逃选透逐途通速造逼遇道遗避那邪邮郁郑部都配酒酪酱酸醉释里重野量金针钉钓钙钟钩钱钻铀铁铃铅银销锁锅锋锐错锤键锻镇镖镜长门闪闭问间闹阅队阱防阴阵阶阻附陆陌降限院除险陷随隐隔隙障难雅集雨雪零雷雾需霆震霜露霸青静非靠面靴鞋音页项须顾领频颗题颜额风飞食餐饭饮饰饱饿馆首香马验骨高鬼魂魔鱼鲜鲸鸟鸡鸣鹅黄黑默鼓鼠龄龙龟";
    global.font = font_add_sprite_ext(s_font_zh, mapstring, true, 1);
    mapstring = "ABCDEFGHIJKLMNOPQRSTUVWXYZ !'#$%&'()*+,-./:;<=>?@[]^_`{}'0123456789";
    global.font_simple = font_add_sprite_ext(s_font_simple, mapstring, true, 1);
    mapstring = "ABCDEFGHIJKLMNOPQRSTUVWXYZ !'#$%&'()*+,-./:;<=>?@[]^_`{}'0123456789";
    global.font_big = font_add_sprite_ext(s_font_big, mapstring, true, 1);
    mapstring = "0123456789HST<KM:.%/+-x(),";
    global.font_mini = font_add_sprite_ext(s_font_mini, mapstring, true, 1);
    mapstring = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789?";
    global.font_small = font_add_sprite_ext(s_font_small, mapstring, true, 1);
    mapstring = "0123456789LV";
    global.font_level = font_add_sprite_ext(s_font_level, mapstring, true, 1);
    mapstring = "0123456789";
    global.font_dmg_base = font_add_sprite_ext(s_font_dmg_base, mapstring, true, 1);
    global.font_dmg_critical = font_add_sprite_ext(s_font_dmg_critical, mapstring, true, 1);
    global.font_dmg_damage = font_add_sprite_ext(s_font_dmg_damage, mapstring, true, 1);
    global.font_dmg_heal = font_add_sprite_ext(s_font_dmg_heal, mapstring, true, 1);
    mapstring = "0123456789%";
    global.font_hs_st = font_add_sprite_ext(s_font_highscore_st, mapstring, true, 1);
    global.font_hs_nd = font_add_sprite_ext(s_font_highscore_nd, mapstring, true, 1);
    global.font_hs_rd = font_add_sprite_ext(s_font_highscore_rd, mapstring, true, 1);
    global.font_hs_th = font_add_sprite_ext(s_font_highscore_th, mapstring, true, 1);
    global.f_tactics_basic = global.font;
    global.f_tactics_small = global.font;
    mapstring = "0123456789/";
    global.f_tactics_unit_count = font_add_sprite_ext(s_font_unit_count, mapstring, true, 2);
    mapstring = "0123456789";
    global.f_tactics_damage = font_add_sprite_ext(s_font_dmg_base, mapstring, true, -1);
    global.f_tactics_critical = font_add_sprite_ext(s_font_dmg_critical, mapstring, true, -1);
    global.f_tactics_heal = font_add_sprite_ext(s_font_dmg_heal, mapstring, true, -1);
}
